### ISSUE TITLE
[Request] Adding function for Volume snapshots

### ISSUE THREAD

**Issue by rmnijgh** [houtknots/Openstack-Automatic-Snapshot#1]
Hi,

I have allot of separate Volumes. Could it be possible to add a function in this script so we can backup volumes?

Like to hear from you

**Comment by njwedwards** [comment]
+1 for this, I think it takes a snapshot of the volume but it does not remove it.

**Comment by houtknots** [comment]
@rmnijgh @njwedwards I will build the functionality into the script soon.

**Comment by houtknots** [comment]
I just pushed a new version which includes automatic volume snapshots. If you have any suggestions, please let me know 😁

**Comment by njwedwards** [comment]
Thanks, been testing and looks good. I did submit some small changes which you should have received.
